import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  logo: {
    backgroundColor: '#0D0D0D',
    height: 173,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: '#1E1E1E',
  },
  formulario: {
    flexDirection: 'row',
    marginTop: -30,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
    justifyContent: 'center',
  },
  formTextInput: {
    flex: 1,
    height: 56,
    backgroundColor: '#262626',
    borderRadius: 10,
    color: '#FFFFFF',
    padding: 16,
    marginRight: 10,
    fontSize: 14,
    borderWidth: 2,
    borderColor: '#262626',
    fontFamily: 'Inter_400Regular',
  },
  estaSelecionado: {
    borderColor: '#8284FA',
  },
  button: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: '#1E6F9F',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  contadorFrom: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginLeft: 20,
    marginRight: 20,
  },
  contador: {
    fontSize: 16,
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'Inter_700Bold',
  },
  contadorTexto: {
    width: 70,
    maxHeight: 25,
    borderRadius: 10, // no ios não a pegou essa borda arredondada :c(
    backgroundColor: '#333333',
    textAlign: 'center',
    fontSize: 16,
    color: '#FFFFFF',
    fontFamily: 'Inter_700Bold',
  },
  separador: {
    marginVertical: 20,
    borderBottomWidth: 3,
  },
  separadorGradient: {
    height: 3,
    marginLeft: 20,
    marginRight: 20,
    marginTop: 20,
    marginBottom: 20,
    opacity: 0.7,
  },
  formLista: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#262626',
    borderRadius: 10,
    marginTop: 20,
    marginBottom: 10,
    marginLeft: 20,
    marginRight: 20,
    height: 80,
  },
  criadoAt: {
    color: '#808080',
    fontSize: 8,
    textAlign: 'center',
    marginLeft: -20,
    marginTop: -22,
    fontFamily: 'Inter_400Regular',
  },
  contentTarefa: {
    flex: 1,
    fontSize: 14,
    padding: 5,
    textAlign: 'justify',
    fontFamily: 'Inter_400Regular',
  },
  clipboard: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  listaVazia: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
  },
})
